dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - pip install pipenv
  - pipenv run pip install pip==18.0

install: pipenv install --skip-lock --dev .

script:
  - pylint -E mistygrind
  - cd tests && pytest -v --aiohttp-enable-loop-debug --aiohttp-loop=pyloop

notifications:
  email:
    recipients:
      - scott@rerobots.net
    on_success: change
    on_failure: always
